/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/watermark.ts
 * Command: astryx theme build src/themes/watermark.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/**
 * watermark theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { watermarkTheme } from './watermark';
 *   import './watermark.css';
 */
export const watermarkTheme = {
  name: 'watermark',
  __built: true,
  tokens: {
    "--color-neutral": "light-dark(#1B1B1F1A, #E2E2E833)",
    "--color-background-surface": "#FFFFFF",
    "--color-background-body": "#FFFFFF",
    "--color-overlay": "light-dark(#1B1B1F66, #1B1B1F99)",
    "--color-overlay-hover": "light-dark(#1B1B1F0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1B1B1F1A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#1B1B1F0D, #1B1B1F80)",
    "--color-text-primary": "#111111",
    "--color-text-secondary": "light-dark(#46464F, #AAAAB5)",
    "--color-text-disabled": "light-dark(#8F909A, #5D5E67)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "#111111",
    "--color-icon-secondary": "light-dark(#46464F, #AAAAB5)",
    "--color-icon-disabled": "light-dark(#8F909A, #5D5E67)",
    "--color-background-card": "#F3F3F3",
    "--color-background-popover": "#FFFFFF",
    "--color-background-inverted": "light-dark(#1B1B1F, #FCFCFF)",
    "--color-border": "light-dark(#1B1B1F1A, #F0F0F61A)",
    "--color-border-emphasized": "light-dark(#92929D, #676771)",
    "--color-skeleton": "light-dark(#AAAAB5, #46464F)",
    "--color-track": "light-dark(#AAAAB5, #46464F)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-family-body": "\"Die Grotesk C\", system-ui, sans-serif",
    "--font-family-heading": "\"Die Grotesk C\", system-ui, sans-serif",
    "--color-accent": "#B7E4F8",
    "--color-on-accent": "#111111",
    "--font-weight-semibold": "500",
    "--font-weight-bold": "500",
    "--text-heading-1-size": "32px",
    "--text-heading-1-leading": "0.8125",
    "--text-heading-2-size": "24px",
    "--text-heading-2-leading": "1.5",
    "--text-heading-3-size": "20px",
    "--text-heading-3-leading": "1.2",
    "--text-heading-4-size": "16px",
    "--text-heading-4-leading": "1.5",
    "--text-body-size": "16px",
    "--text-body-leading": "1.5",
    "--text-large-size": "20px",
    "--text-large-leading": "1.2",
    "--text-label-size": "16px",
    "--text-label-leading": "1.5",
    "--text-supporting-size": "16px",
    "--text-supporting-leading": "1.5",
    "--text-code-size": "16px",
    "--text-display-1-size": "96px",
    "--text-display-1-leading": "0.8",
    "--text-display-2-size": "64px",
    "--text-display-2-leading": "0.8",
    "--text-display-3-size": "24px",
    "--text-display-3-leading": "1.5"
  },
  components: {
    "heading": {
      "base": {
        "letterSpacing": "-0.03em"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "body": {
        "family": "Die Grotesk C",
        "fallbacks": "system-ui, sans-serif"
      }
    },
    "color": {
      "neutralStyle": "neutral",
      "contrast": "standard"
    }
  },

};
