/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/watermark.ts
 * Command: astryx theme build src/themes/watermark.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Button' {
  interface ButtonVariantMap {
    'wallet': true;
    'wallet-connected': true;
  }
}
