/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/watermark.ts
 * Command: astryx theme build src/themes/watermark.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/**
 * watermark theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { watermarkTheme } from './watermark';
 *   import './watermark.css';
 */
export const watermarkTheme = {
  name: 'watermark',
  __built: true,
  tokens: {
    "--color-neutral": "light-dark(#1B1B1F1A, #E2E2E833)",
    "--color-background-surface": "#F3F3F3",
    "--color-background-body": "#B7E4F8",
    "--color-overlay": "light-dark(#1B1B1F66, #1B1B1F99)",
    "--color-overlay-hover": "light-dark(#1B1B1F0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1B1B1F1A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#1B1B1F0D, #1B1B1F80)",
    "--color-text-primary": "#111111",
    "--color-text-secondary": "light-dark(#46464F, #AAAAB5)",
    "--color-text-disabled": "light-dark(#8F909A, #5D5E67)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "#111111",
    "--color-icon-secondary": "light-dark(#46464F, #AAAAB5)",
    "--color-icon-disabled": "light-dark(#8F909A, #5D5E67)",
    "--color-background-card": "#FFFFFF",
    "--color-background-popover": "#FFFFFF",
    "--color-background-inverted": "light-dark(#1B1B1F, #FCFCFF)",
    "--color-border": "light-dark(#1B1B1F1A, #F0F0F61A)",
    "--color-border-emphasized": "light-dark(#92929D, #676771)",
    "--color-skeleton": "light-dark(#AAAAB5, #46464F)",
    "--color-track": "light-dark(#AAAAB5, #46464F)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.1875rem",
    "--font-size-xl": "1.4375rem",
    "--font-size-2xl": "1.75rem",
    "--font-size-3xl": "2.0625rem",
    "--font-size-4xl": "2.5rem",
    "--font-size-5xl": "3rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.4286",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.3913",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4737",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4737",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.25",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.3",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2121",
    "--font-family-body": "\"Die Grotesk C\", system-ui, sans-serif",
    "--font-family-heading": "\"Die Grotesk C\", system-ui, sans-serif",
    "--color-accent": "#111111",
    "--color-on-accent": "#FFFFFF",
    "--font-weight-semibold": "500",
    "--font-weight-bold": "500"
  },
  localTokens: {
    "--watermark-water": "#0080BC",
    "--watermark-water-strong": "#0077AF",
    "--font-family-wordmark": "\"LisaTerminal Paper\", \"Courier New\", monospace"
  },
  __localTokenOwners: {
    "--watermark-water": "watermark",
    "--watermark-water-strong": "watermark",
    "--font-family-wordmark": "watermark"
  },
  __localTokenLineage: ["watermark"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "type:wordmark": {
        "fontFamily": "var(--font-family-wordmark)",
        "fontWeight": "var(--font-weight-normal)",
        "color": "var(--color-text-primary)"
      },
      "type:wordmark-water": {
        "fontFamily": "var(--font-family-wordmark)",
        "fontWeight": "var(--font-weight-normal)",
        "color": "var(--watermark-water)"
      }
    },
    "app-shell-header": {
      "variant:wash": {
        "backgroundColor": "var(--color-background-card)",
        "margin": "var(--spacing-3) var(--spacing-4) 0",
        "borderRadius": "var(--radius-container)"
      }
    },
    "button": {
      "variant:wallet": {
        "backgroundColor": "var(--color-background-card)",
        "backgroundImage": "radial-gradient(var(--color-background-body) 0.92px, transparent 1px)",
        "backgroundSize": "2px 2px",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "var(--color-text-primary)",
        "borderRadius": "var(--radius-full)",
        "color": "var(--color-text-primary)"
      },
      "variant:wallet-connected": {
        "backgroundColor": "var(--watermark-water-strong)",
        "borderRadius": "var(--radius-full)",
        "color": "var(--color-on-accent)"
      }
    },
    "banner": {
      "container:section": {
        "backgroundColor": "var(--color-background-surface)",
        "color": "var(--color-text-primary)",
        "fontFamily": "var(--font-family-wordmark)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 16,
        "ratio": 1.2
      },
      "body": {
        "family": "Die Grotesk C",
        "fallbacks": "system-ui, sans-serif"
      }
    },
    "color": {
      "neutralStyle": "neutral",
      "contrast": "standard"
    }
  },

};
