/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/watermark.ts
 * Command: astryx theme build src/themes/watermark.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const watermarkTheme: DefinedTheme;
